import {latest, records, countries, types, countryName, recordPath, filterRecords} from './catalog.js';
export const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repo = 'https://github.com/Yamans86/anticipatory-action';
const nav = [['/','Home'],['/why','Why this matters'],['/evidence','Evidence'],['/countries/CA','Canada Lab'],['/early-warning','Early Warning'],['/actions','Actions'],['/methodology','Methodology'],['/project','Project']];
const arrow = '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 12h16m-7-7 7 7-7 7"/></svg>';
export function layout(title, content, path) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Evidence-first research on AI-related labour-market change and anticipatory action. Canada pilot; transparent sources, methods and limitations."><title>${esc(title)} | Anticipatory Action</title><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/">Anticipatory Action<span>Research platform</span></a><nav aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}" ${path===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${content}</main><footer><span>Version 0.1.0 · Research scaffold</span><div><a href="/methodology">Methodology</a><a href="${repo}">Source code</a><a href="/api/catalog.json">Download catalog</a></div></footer></body></html>`;
}
const intro = (title,desc) => `<div class="intro"><h1>${esc(title)}</h1><p class="lead">${esc(desc)}</p></div>`;
const notice = '<div class="notice">Research in development. No validated warning model or operational triggers.</div>';
const row = (href,title,desc) => `<a class="editorial-row" href="${href}"><h3>${esc(title)}</h3><span>${esc(desc)}</span>${arrow}</a>`;
export function home() {
  const stages = [['Source','Track credible sources on AI adoption and labour-market change.','/evidence'],['Indicator','Identify and test potential indicators of labour-market stress.','/indicators'],['Experiment','Evaluate indicators, starting with the Canada pilot.','/experiments'],['Model','Develop predictive approaches with transparent limits.','/early-warning'],['Action','Inform earlier, accountable support for people at risk.','/actions']];
  return `<section class="hero"><div><h1>Understand change.<br>Act before harm.</h1><p class="lead">Tracing the evidence from AI-related labour-market change to earlier, accountable support.</p><div class="hero-links"><a href="/evidence">Explore the evidence ${arrow}</a><a href="/countries/CA">Visit Canada Lab ${arrow}</a></div></div><ol class="chain">${stages.map(([t,d,h])=>`<li><a href="${h}">${t}</a><p>${d}</p></li>`).join('')}</ol></section>${notice}<section class="question"><div><p class="label">Start with the question</p><h2>Can changes associated with AI adoption help us detect labour-market stress early enough to support people at risk?</h2></div><div><p class="label">Current pilot: Canada</p><h2>Definitions first.<br>Data and validation next.</h2></div></section><section aria-label="Explore the research">${row('/evidence','Evidence and data','Follow sources and limitations.')}${row('/countries/CA','Canada Lab','Inspect proposed indicators and experiments.')}${row('/methodology','Methods and decisions','See how the research develops.')}</section>`;
}
function table(items) {
  if (!items.length) return '<p class="empty" role="status">No records match these filters. Try a broader search or reset the filters.</p>';
  return `<div class="table-scroll"><table><caption class="sr-only">Research records</caption><thead><tr><th scope="col">Record</th><th scope="col">Type</th><th scope="col">Country</th><th scope="col">Status</th></tr></thead><tbody>${items.map(r=>`<tr><td><a href="${recordPath(r)}">${esc(r.title)}</a><small>${r.id} · v${r.version}</small></td><td class="capitalize">${r.type}</td><td>${countryName(r.country)}</td><td class="capitalize">${r.status}</td></tr>`).join('')}</tbody></table></div>`;
}
export function catalog(url, allowed = types, title='Research catalog', desc='Follow each research object and its evidence chain.') {
  const q=url.searchParams.get('q')||'', type=url.searchParams.get('type')||'', country=url.searchParams.get('country')||'';
  const items=filterRecords({q,type,country},latest.filter(r=>allowed.includes(r.type)));
  return `${intro(title,desc)}<form class="filters" method="get"><label>Search records<input name="q" value="${esc(q)}" placeholder="Search by title, keyword or ID…" maxlength="200"></label><label>Type<select name="type"><option value="">All types</option>${allowed.map(t=>`<option value="${t}" ${t===type?'selected':''}>${t}</option>`).join('')}</select></label><label>Country<select name="country"><option value="">All countries</option>${countries.map(c=>`<option value="${c.code}" ${c.code===country?'selected':''}>${c.name}</option>`).join('')}</select></label><button>Filter</button></form><div class="result-meta"><span>${items.length} record${items.length===1?'':'s'}</span><a href="${esc(url.pathname)}">Reset filters</a></div>${table(items)}<section class="prose"><h2>What a record tells you</h2><p>Every record carries a permanent ID, version, provenance, limitations and links to related research. A link shows a dependency or proposed use; it does not imply that the evidence has validated the downstream object.</p><p><a href="/catalog">Browse all research objects</a> · <a href="/api/catalog.json">Download the versioned catalog</a></p></section>`;
}
export function detail(r) {
  const dependents=records.filter(x=>x.links.some(l=>l.id===r.id&&l.version===r.version));
  const links=rs=>rs.length?`<ul>${rs.map(x=>`<li><a href="${recordPath(x)}">${esc(x.title)}</a> <small>v${x.version}</small></li>`).join('')}</ul>`:'<p>None recorded in this release.</p>';
  return `<p class="breadcrumb"><a href="/catalog">Research catalog</a> / ${esc(r.type)}</p>${intro(r.title,r.summary)}<div class="detail-layout"><article class="prose"><h2>Purpose</h2><p>${esc(r.body)}</p><h2>Limitations</h2><ul>${r.limitations.map(l=>`<li>${esc(l)}</li>`).join('')}</ul><h2>Specification</h2><dl>${Object.entries(r.details).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><h2>Evidence and dependencies</h2>${r.links.length?`<ul>${r.links.map(l=>`<li>${esc(l.relation)}: <a href="/objects/${l.id}/v/${l.version}">${l.id} · v${l.version}</a></li>`).join('')}</ul>`:'<p>No upstream research objects recorded.</p>'}<h2>Used by</h2>${links(dependents)}<h2>Provenance</h2><dl>${Object.entries(r.provenance).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${k==='url'&&v?`<a href="${esc(v)}">Publisher source</a>`:esc(v??'Not available — no executed data or code artifact')}</dd>`).join('')}</dl></article><aside aria-label="Record metadata"><dl><dt>Permanent ID</dt><dd><code>${r.id}</code></dd><dt>Version</dt><dd>${r.version}</dd><dt>Status</dt><dd class="capitalize">${r.status}</dd><dt>Country</dt><dd>${countryName(r.country)}</dd><dt>Updated</dt><dd>${r.updated}</dd></dl><p><a href="${recordPath(r)}">Version permalink</a></p><p><a href="/api/objects/${r.id}/v/${r.version}.json">Download record JSON</a></p><p><a href="${repo}/commits/main/content/records.json">Editorial history</a></p><h3>Available versions</h3>${links(records.filter(x=>x.id===r.id))}</aside></div>`;
}
export function countryPage(c) {
  return `${intro(`${c.name} Lab`,c.description)}${notice}<section class="prose"><h2>Research status: ${c.stage}</h2><p>The first task is to agree the target population, plausible risk pathways and what would count as a useful warning. Country membership does not imply that an indicator is comparable across borders.</p><p><a href="/indicators">Indicators</a> · <a href="/experiments">Experiments</a> · <a href="/countries">All country labs</a></p></section>${table(latest.filter(r=>r.country===c.code))}`;
}
const prose = body => `<article class="prose wide">${body}</article>`;
export const staticPages = {
  '/why': ['Why this matters',()=>intro('Why this matters','Earlier support begins with a better understanding of change.')+prose('<h2>The question we are investigating</h2><p>This project asks whether changes associated with AI adoption could provide useful warning of labour-market stress among economically vulnerable people. This is a research question, not an established finding.</p><h2>From a signal to a decision</h2><p>A change in an employment measure needs interpretation. It may reflect many influences, and it does not explain who needs support or which intervention will help. The platform connects sources, definitions, experiments and limitations so readers can inspect that reasoning.</p><h2>Who this is for</h2><p>Researchers, public institutions and humanitarian or social-protection practitioners who need to understand both the potential and the limits of anticipatory approaches.</p><p><a href="/countries/CA">Start with the Canada pilot</a></p>')],
  '/early-warning':['Early Warning',()=>intro('Early warning, with evidence','No live warning model is active.')+notice+prose('<h2>A proposed risk pathway</h2><p>AI-related changes in work may affect demand for particular tasks; changes in employment or earnings may then affect household resilience. Each link requires evidence. Other economic forces must be considered.</p><h2>Before any alert can be used</h2><ol><li>Define the outcome, population and forecast horizon.</li><li>Validate using time-separated data and compare against a simple baseline.</li><li>Publish uncertainty, false alarms, missed events and subgroup performance.</li><li>Agree an accountable decision owner, feasible response and stop rules.</li></ol><p>Unknown or stale evidence must remain unknown. It must never appear as a green or low-risk signal.</p>')+table(latest.filter(r=>r.type==='model'))],
  '/actions':['Anticipatory actions',()=>intro('Anticipatory actions','Connect reviewed evidence to accountable decisions.')+prose('<p>Actions are currently proposals. No trigger, operational partner, budget or delivery commitment has been approved. Each future action must specify who decides, who benefits, lead time, resources, safeguards and when to stop.</p>')+table(latest.filter(r=>r.type==='action'))],
  '/methodology':['Methodology',()=>intro('Make the reasoning inspectable','A result is only useful when its evidence, assumptions and limits travel with it.')+prose('<h2>Permanent identity and versions</h2><p>Objects retain a permanent ID even when their title changes. Version-specific links pin the exact record used. Published versions are retained; corrections create a new version and explain what changed. The unversioned object URL redirects to its latest version.</p><h2>Evidence is not a status shortcut</h2><p>Catalogued means a source has been described. Proposed, planned and concept records have not been validated. A dependency link records intended use, not proof. Validation requires a documented review and reproducible results.</p><h2>Reproducibility</h2><p>Executed work must identify original data releases, retrieval dates, licences, file checksums, transformation code commits, environment, parameters and run logs. This release includes metadata only; null artifact fields mean no analysis has been executed.</p><h2>Analysis and uncertainty</h2><p>Pre-specify outcomes and evaluation windows. Use time-aware splits, avoid future-information leakage, compare baselines and retain failed or null results. Distinguish causal claims from prediction. Report sampling error, revisions, missingness and subgroup limitations.</p><h2>Across countries</h2><p>Each record is attached to a country registry entry. Additional country labs use the same object types but retain local definitions, institutional context and source licences. Cross-country comparison requires an explicit harmonisation protocol.</p><h2>Editorial workflow</h2><p>Propose changes in Git, add a versioned record, validate references and provenance, review the limitations and update the changelog. Existing published versions must not be edited or removed. The site is built from those records.</p><p><a href="/catalog">Inspect the catalog</a> · <a href="/project">Read project decisions</a></p>')],
  '/project':['Project',()=>intro('A research platform in the open','Track what is built, what is proposed and what comes next.')+prose('<h2>Project history</h2><p>The supplied project brief sets out an evidence-first platform, with Canada as the initial pilot and room for other countries. The earlier discussion preview proposed six layers: narrative, evidence, analytical objects, results, anticipatory action and reproducibility.</p><p>On 26 September 2026, this initial skeleton was prepared. Earlier research files were not available in the synced reference folder, so no previous results or historical milestones have been reconstructed.</p><h2>Architecture decision · ADR-001</h2><p>Use server-rendered HTML, a small Node service and versioned JSON records in Git. No database or client framework is needed for this read-only release. Separate the catalog from presentation so future ingestion pipelines or a database can preserve existing object IDs and URLs.</p><h2>Results register</h2><p>No completed experiments or findings are published. Future results must link to the exact experiment version, data manifest and code commit, including unsuccessful tests.</p><p><a href="/roadmap">Roadmap</a> · <a href="/changelog">Changelog</a> · <a href="/countries">Country registry</a></p>')],
  '/roadmap':['Roadmap',()=>intro('Roadmap','Sequence the research before expanding the interface.')+prose('<h2>Now · Foundation</h2><p>Permanent object IDs, versioned catalog, Canada Lab, research status, evidence links and public methods.</p><h2>Next · Source and protocol review</h2><p>Recover prior research with provenance. Select precise data releases, assess licensing, define vulnerable populations and review indicator definitions. Identify a credible AI adoption or exposure source.</p><h2>Then · Reproducible analysis</h2><p>Implement ingestion manifests and checksums. Pre-register an experiment and publish baseline, null and positive results with reproducible run artifacts.</p><h2>Later · Decision validation</h2><p>Review model performance, thresholds, community impacts and action feasibility before any operational alert. Add countries only with local evidence and explicit comparability limits.</p><p>These are proposed stages, not delivery dates or funded commitments.</p>')],
  '/changelog':['Changelog',()=>intro('Changelog','Changes to the platform and its research records.')+prose('<h2>0.1.0 · 26 September 2026</h2><ul><li>Initial public research skeleton with narrative, evidence catalog and Canada Lab.</li><li>Seven source and proposed research records with permanent IDs and version-specific links.</li><li>Early-warning concept and action proposal explicitly labelled inactive or unvalidated.</li><li>Methodology, history, roadmap, JSON exports and deployment configuration.</li></ul><p>This release contains no ingested observations, executed experiments or validated findings.</p>')],
  '/countries':['Country labs',()=>intro('Country labs','Shared structure. Local evidence and definitions.')+countries.map(c=>row(`/countries/${c.code}`,`${c.name} · ${c.stage}`,c.description)).join('')]
};
